version: "2"
services:
  app:
    image: institutoupdate/liane:latest
    restart: unless-stopped
    links:
      - mongo
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./.data/files:/opt/meteor/dist/bundle/generated-files
    environment:
      NODE_ENV: production
      ROOT_URL: https://example.com
      MONGO_URL: mongodb://mongo:27017/meteor
      STARTUP_DELAY: 5
      METEOR_SETTINGS: |-
        {
          "public": {
            "deployMode": "production",
            "domain": "example.com",
            "appName": "Liane",
            "appEmail": "contact@example.com",
            "termsUrl": "<URL FOR YOUR TERMS OF USE>",
            "privacyUrl": "<URL FOR YOUR PRIVACY POLICY>",
            "recaptcha": "<YOUR RECAPTCHA PUBLIC KEY>",
            "analyticsSettings": {
              "Google Analytics": { "trackingId": "<GOOGLE ANALYTICS TRACKING ID>" }
            }
          },
          "filesUrl": "https://files.example.com",
          "recaptcha": "<YOUR RECAPTCHA PRIVATE KEY>",
          "googleMaps": "<GOOGLE MAPS API KEY>",
          "webhookToken": "<SELF-GENERATED WEBHOOK API TOKEN>",
          "private": true,
          "facebook": {
            "clientId": "<YOUR APP ID>",
            "clientSecret": "<YOUR APP SECRET>"
          },
          "redis": {
            "host": "redis",
            "port": "6379"
          },
          "email": {
            "mail": {
              "host": "smtp.gmail.com",
              "port": 587,
              "username": "contact@example.com",
              "password": "x",
              "admins": ["contact@example.com"]
            },
            "admins": ["contact@example.com"]
          }
        }
  files_server:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 3001:80
    volumes:
      - ./.data/files-server-conf:/etc/nginx/conf.d
      - ./.data/files:/var/www/html
  webhooks:
    image: institutoupdate/liane-webhooks:latest
    restart: unless-stopped
    environment:
      NODE_CONFIG: |-
        {
          "url": "https://webhooks.example.com",
          "facebook": {
            "clientId": "<YOUR APP ID>",
            "clientSecret": "<YOUR APP SECRET>",
            "webhookVerifyToken": "<TOKEN VERIFICATION SECRET>",
            "fields": [
              "feed"
            ]
          },
          "services": {
            "liane": {
              "type": "ddp",
              "methodName": "webhookUpdate",
              "host": "example.com",
              "port": 443,
              "token": "<SELF-GENERATED WEBHOOK API TOKEN>",
              "fields": ["feed", "comments"],
              "test": false
            }
          }
        }
      ENV: production
  mongo:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./.data/database:/data/db
  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - ./.data/redis:/data
